export const theme = {
  colors: {
    background: '#f5f0e8',
    surface: '#faf7f2',
    surfaceAlt: '#ede8de',
    primary: '#1a3c5e',
    primaryDark: '#122a44',
    secondary: '#8b6914',
    accent: '#2e5e2e',
    gold: '#c4a035',
    goldLight: '#e8c95a',
    text: '#2d2d2d',
    textMuted: '#6b6b6b',
    textLight: '#999',
    border: '#d4cfc5',
    borderDark: '#bfb9ad',
    userBubble: '#1a3c5e',
    userBubbleText: '#ffffff',
    white: '#ffffff',
    error: '#c0392b',
  },
  fonts: {
    heading: "'Georgia', 'Times New Roman', serif",
    body: "'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    mono: "'Courier New', monospace",
  },
  radii: {
    sm: '4px',
    md: '8px',
    lg: '16px',
    xl: '24px',
    pill: '999px',
  },
  shadows: {
    sm: '0 1px 3px rgba(0,0,0,0.08)',
    md: '0 2px 8px rgba(0,0,0,0.1)',
    lg: '0 4px 20px rgba(0,0,0,0.12)',
  },
};
